2019-11-04 15:54:55,663 - __main__ - ERROR - Error in DB - name 'logger' is not defined
2019-11-04 15:54:55,664 - __main__ - INFO - Finished inserting records.
2019-11-04 15:58:14,939 - __main__ - ERROR - Error in connection - FATAL:  password authentication failed for user "postgres"

2019-11-04 15:58:14,940 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 15:58:14,940 - __main__ - INFO - Finished inserting records.
2019-11-04 15:58:38,289 - __main__ - ERROR - Error in connection - FATAL:  password authentication failed for user "postgres"

2019-11-04 15:58:38,290 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 15:58:38,290 - __main__ - INFO - Finished inserting records.
2019-11-04 15:59:29,616 - __main__ - ERROR - Error in connection - FATAL:  database "test_db" does not exist

2019-11-04 15:59:29,616 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 15:59:29,617 - __main__ - INFO - Finished inserting records.
2019-11-04 16:01:24,017 - __main__ - ERROR - Error in connection - FATAL:  database "test_db" does not exist

2019-11-04 16:01:24,018 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:01:24,018 - __main__ - INFO - Finished inserting records.
2019-11-04 16:06:57,995 - __main__ - ERROR - Error in connection - FATAL:  database "test_db" does not exist

2019-11-04 16:06:57,995 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:06:57,996 - __main__ - INFO - Finished inserting records.
2019-11-04 16:08:25,227 - __main__ - ERROR - Error in connection - FATAL:  password authentication failed for user "postgres"

2019-11-04 16:08:25,227 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:08:25,228 - __main__ - INFO - Finished inserting records.
2019-11-04 16:10:32,718 - __main__ - ERROR - Error in connection - FATAL:  database "test_db" does not exist

2019-11-04 16:10:32,719 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:10:32,719 - __main__ - INFO - Finished inserting records.
2019-11-04 16:10:50,636 - __main__ - ERROR - Error in connection - FATAL:  database "test_db" does not exist

2019-11-04 16:10:50,637 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:10:50,638 - __main__ - INFO - Finished inserting records.
2019-11-04 16:11:40,584 - __main__ - ERROR - Error in connection - FATAL:  database "test_db" does not exist

2019-11-04 16:11:40,586 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:11:40,586 - __main__ - INFO - Finished inserting records.
2019-11-04 16:12:01,672 - __main__ - ERROR - Error in connection - FATAL:  database "test_db" does not exist

2019-11-04 16:12:01,673 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:12:01,673 - __main__ - INFO - Finished inserting records.
2019-11-04 16:12:37,890 - __main__ - INFO - Finished inserting records.
2019-11-04 16:22:36,021 - __main__ - ERROR - Error in DB - module 'create_db_table' has no attribute 'table'
2019-11-04 16:22:36,021 - __main__ - INFO - Finished inserting records.
2019-11-04 16:25:20,176 - __main__ - INFO - Finished inserting records.
2019-11-04 16:41:11,982 - __main__ - ERROR - Error in connection - FATAL:  password authentication failed for user "postgres"

2019-11-04 16:41:11,983 - __main__ - ERROR - 'NoneType' object has no attribute 'cursor'
2019-11-04 16:41:11,984 - __main__ - INFO - Finished inserting records.
2019-11-04 16:41:34,710 - __main__ - INFO - Finished inserting records.
2019-11-04 16:42:18,298 - __main__ - ERROR - Unable to insert record - null value in column "datetime" violates not-null constraint
DETAIL:  Failing row contains (1, null, ., config.ini, 118, 75e2f21c692cb4fe6601f3c417b72350, 8aeced47bad30e683a0e071fe4edc7ba48ae9b9a).

2019-11-04 16:42:18,299 - __main__ - INFO - Finished inserting records.
2019-11-04 16:43:29,740 - __main__ - INFO - Finished inserting records.
2019-11-04 16:45:43,923 - __main__ - INFO - Finished inserting records.
2019-11-04 16:48:30,268 - __main__ - INFO - Finished inserting records.
2019-11-04 17:02:31,538 - __main__ - INFO - Naming default_file
2019-11-04 17:02:31,539 - __main__ - INFO - Result: default_file_20191104_170231
2019-11-04 17:02:31,539 - __main__ - INFO - Opening new .csv file.
2019-11-04 17:02:31,539 - __main__ - INFO - Including the ff. headers: ['Parent Path', 'File Name', 'File Size', 'MD5', 'SHA1'].
2019-11-04 17:02:31,540 - __main__ - INFO - Writing rows...
2019-11-04 17:02:31,552 - __main__ - INFO - Finished with .csv file. Onto zipping...
2019-11-04 17:02:31,552 - __main__ - INFO - Zipping default_file_20191104_170231.csv
2019-11-04 17:02:31,553 - __main__ - INFO - Creating zip...
2019-11-04 17:02:31,557 - __main__ - INFO - Zipping done.
2019-11-04 17:02:31,558 - __main__ - INFO - Finished creating default_file_20191104_170231.csv.zip.
2019-11-04 17:04:31,704 - __main__ - INFO - Naming default_file
2019-11-04 17:04:31,705 - __main__ - INFO - Result: default_file_20191104_170431
2019-11-04 17:04:31,705 - __main__ - INFO - Opening new .csv file.
2019-11-04 17:04:31,706 - __main__ - INFO - Including the ff. headers: ['Parent Path', 'File Name', 'File Size', 'MD5', 'SHA1'].
2019-11-04 17:04:31,706 - __main__ - INFO - Writing rows...
2019-11-04 17:04:31,722 - __main__ - INFO - Finished with .csv file. Onto zipping...
2019-11-04 17:04:31,722 - __main__ - INFO - Zipping default_file_20191104_170431.csv
2019-11-04 17:04:31,723 - __main__ - INFO - Creating zip...
2019-11-04 17:04:31,727 - __main__ - INFO - Zipping done.
2019-11-04 17:04:31,728 - __main__ - INFO - Finished creating default_file_20191104_170431.csv.zip.
2019-11-04 17:04:45,116 - __main__ - INFO - Naming default_file
2019-11-04 17:04:45,117 - __main__ - INFO - Result: default_file_20191104_170445
2019-11-04 17:04:45,117 - __main__ - INFO - Opening new .csv file.
2019-11-04 17:04:45,118 - __main__ - INFO - Including the ff. headers: ['Parent Path', 'File Name', 'File Size', 'MD5', 'SHA1'].
2019-11-04 17:04:45,118 - __main__ - INFO - Writing rows...
2019-11-04 17:04:45,134 - __main__ - INFO - Finished with .csv file. Onto zipping...
2019-11-04 17:04:45,134 - __main__ - INFO - Zipping default_file_20191104_170445.csv
2019-11-04 17:04:45,135 - __main__ - INFO - Creating zip...
2019-11-04 17:04:45,141 - __main__ - INFO - Zipping done.
2019-11-04 17:04:45,141 - __main__ - INFO - Finished creating default_file_20191104_170445.csv.zip.
2019-11-04 17:06:53,344 - __main__ - INFO - Finished inserting records.
2019-11-04 17:07:28,858 - __main__ - INFO - Finished inserting records.
2019-11-04 17:08:55,801 - __main__ - INFO - Naming default_file
2019-11-04 17:08:55,802 - __main__ - INFO - Result: default_file_20191104_170855
2019-11-04 17:08:55,802 - __main__ - INFO - Opening new .csv file.
2019-11-04 17:08:55,802 - __main__ - INFO - Including the ff. headers: ['Parent Path', 'File Name', 'File Size', 'MD5', 'SHA1'].
2019-11-04 17:08:55,803 - __main__ - INFO - Writing rows...
2019-11-04 17:08:55,815 - __main__ - INFO - Finished with .csv file. Onto zipping...
2019-11-04 17:08:55,815 - __main__ - INFO - Zipping default_file_20191104_170855.csv
2019-11-04 17:08:55,816 - __main__ - INFO - Creating zip...
2019-11-04 17:08:55,822 - __main__ - INFO - Zipping done.
2019-11-04 17:08:55,822 - __main__ - INFO - Finished creating default_file_20191104_170855.csv.zip.
2019-11-04 17:31:42,256 - __main__ - ERROR - Error in DB - name 'create_db_table' is not defined
2019-11-04 17:31:42,263 - __main__ - INFO - Finished inserting records.
2019-11-04 17:34:27,947 - __main__ - ERROR - Error in DB - name 'create_db_table' is not defined
2019-11-04 17:34:27,947 - __main__ - INFO - Finished inserting records.
2019-11-04 17:35:21,024 - __main__ - ERROR - Error in DB - name 'create_db_table' is not defined
2019-11-04 17:35:21,025 - __main__ - INFO - Finished inserting records.
2019-11-04 17:38:38,569 - __main__ - ERROR - Error in DB - name 'create_db_table' is not defined
2019-11-04 17:38:38,570 - __main__ - INFO - Finished inserting records.
2019-11-04 17:41:45,858 - __main__ - ERROR - Error in DB - name 'create_db_table' is not defined
2019-11-04 17:41:45,858 - __main__ - INFO - Finished inserting records.
2019-11-04 17:45:00,604 - __main__ - ERROR - Error in DB - name 'create_db_table' is not defined
2019-11-04 17:45:00,605 - __main__ - INFO - Finished inserting records.
2019-11-04 17:45:40,313 - __main__ - ERROR - Error in DB - name 'create_db_table' is not defined
2019-11-04 17:45:40,313 - __main__ - INFO - Finished inserting records.
2019-11-04 17:48:56,118 - __main__ - INFO - Finished inserting records.
2019-11-04 17:49:35,365 - __main__ - INFO - Finished inserting records.
2019-11-04 17:52:54,293 - __main__ - INFO - Finished inserting records.
2019-11-12 15:46:29,199 - __main__ - INFO - Naming default_file
2019-11-12 15:46:29,208 - __main__ - INFO - Result: default_file_20191112_154629
2019-11-12 15:46:29,209 - __main__ - INFO - Opening new .json file.
2019-11-12 15:46:29,210 - __main__ - INFO - Writing rows...
2019-11-12 15:46:29,335 - __main__ - INFO - Finished with .json file. Onto zipping...
2019-11-12 15:46:29,335 - __main__ - INFO - Zipping default_file_20191112_154629.json
2019-11-12 15:46:29,336 - __main__ - INFO - Creating zip...
2019-11-12 15:46:29,351 - __main__ - INFO - Zipping done.
2019-11-12 15:46:29,351 - __main__ - INFO - Finished creating default_file_20191112_154629.json.zip.
2019-11-12 16:42:03,721 - __main__ - INFO - Naming default_file
2019-11-12 16:42:03,722 - __main__ - INFO - Result: default_file_20191112_164203
2019-11-12 16:42:03,733 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.1.0 connecting to ('::1', 5672, 0, 0)
2019-11-12 16:42:03,734 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=140, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 52077, 0, 0), raddr=('::1', 5672, 0, 0)>
2019-11-12 16:42:03,735 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A72E23A408>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A72E23A408> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2019-11-12 16:42:03,747 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A72E23A408> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 16:42:03,748 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A72E23A408> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 16:42:03,748 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A72E23A408> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 16:42:03,749 - pika.adapters.blocking_connection - INFO - Created channel=1
2019-11-12 16:54:48,091 - __main__ - INFO - Naming default_file
2019-11-12 16:54:48,092 - __main__ - INFO - Result: default_file_20191112_165448
2019-11-12 16:54:48,092 - __main__ - ERROR - Unable to send to queue!
2019-11-12 16:56:32,451 - __main__ - INFO - Naming default_file
2019-11-12 16:56:32,451 - __main__ - INFO - Result: default_file_20191112_165632
2019-11-12 16:56:32,462 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.1.0 connecting to ('::1', 5672, 0, 0)
2019-11-12 16:56:32,463 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=836, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 52126, 0, 0), raddr=('::1', 5672, 0, 0)>
2019-11-12 16:56:32,465 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022475E786C8>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022475E786C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2019-11-12 16:56:32,469 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022475E786C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 16:56:32,470 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022475E786C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 16:56:32,471 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022475E786C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 16:56:32,472 - pika.adapters.blocking_connection - INFO - Created channel=1
2019-11-12 17:03:13,788 - __main__ - INFO - Naming default_file
2019-11-12 17:03:13,788 - __main__ - INFO - Result: default_file_20191112_170313
2019-11-12 17:03:13,800 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.1.0 connecting to ('::1', 5672, 0, 0)
2019-11-12 17:03:13,801 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=768, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 52152, 0, 0), raddr=('::1', 5672, 0, 0)>
2019-11-12 17:03:13,802 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001823FE07748>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001823FE07748> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2019-11-12 17:03:13,807 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001823FE07748> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 17:03:13,808 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001823FE07748> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 17:03:13,809 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001823FE07748> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 17:03:13,810 - pika.adapters.blocking_connection - INFO - Created channel=1
2019-11-12 17:07:31,273 - __main__ - INFO - Naming default_file
2019-11-12 17:07:31,274 - __main__ - INFO - Result: default_file_20191112_170731
2019-11-12 17:07:31,284 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.1.0 connecting to ('::1', 5672, 0, 0)
2019-11-12 17:07:31,285 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=768, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 52181, 0, 0), raddr=('::1', 5672, 0, 0)>
2019-11-12 17:07:31,287 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000139BCD29708>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000139BCD29708> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2019-11-12 17:07:31,293 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000139BCD29708> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 17:07:31,293 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000139BCD29708> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 17:07:31,294 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000139BCD29708> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-12 17:07:31,294 - pika.adapters.blocking_connection - INFO - Created channel=1
2019-11-13 08:30:28,702 - __main__ - INFO - Naming default_file
2019-11-13 08:30:28,715 - __main__ - INFO - Result: default_file_20191113_083028
2019-11-13 08:30:28,727 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.1.0 connecting to ('::1', 5672, 0, 0)
2019-11-13 08:30:28,727 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=720, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 52863, 0, 0), raddr=('::1', 5672, 0, 0)>
2019-11-13 08:30:28,729 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000017249A785C8>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000017249A785C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2019-11-13 08:30:28,734 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000017249A785C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-13 08:30:28,734 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000017249A785C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-13 08:30:28,735 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000017249A785C8> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2019-11-13 08:30:28,735 - pika.adapters.blocking_connection - INFO - Created channel=1
